apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lars-sandbox

commonLabels:
  app: fio-benchmark

resources:
  - pvc-cephfs.yaml
  - pvc-rbd.yaml
  - pvc-nfs.yaml
  - pvc-results.yaml
  - job.yaml
  - pod.yaml
  - service.yaml
  - route.yaml

configMapGenerator:
  - name: fio-scripts
    files:
      - run-benchmark.sh
  - name: fio-config
    files:
      - template.fio
