apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-claim-cephfs
spec:
  storageClassName: ocs-storagecluster-cephfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
