apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-claim-rbd
spec:
  storageClassName: ocs-external-storagecluster-ceph-rbd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
